import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Weekly Meal Plan Generator | Personalized Diet Plans",
  description:
    "Generate a weekly meal plan tailored to your goals. AI meal planner with personalized diet plans and macro-aware suggestions.",
  keywords: [
    "weekly meal plan generator",
    "personalized diet plan",
    "custom meal plan generator",
    "ai meal planner",
    "ai diet plan generator",
  ],
};

const faqs = [
  { q: "Can I export my meal plan?", a: "Yes, download as PNG or PDF for easy sharing and printing." },
  { q: "What if I have allergies?", a: "Apply allergen filters like nuts, dairy or gluten and regenerate the plan." },
  { q: "Can I choose cuisines?", a: "Pick preferences such as Indian, vegetarian or vegan for localized menus." },
];

export default function MealPlansSEOPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
  };

  return (
    <section className="max-w-3xl mx-auto p-6 space-y-4">
      <h1 className="text-2xl font-semibold text-slate-900">Weekly Meal Plans</h1>
      <p className="text-slate-600">Personalized diet plans generated by AI.</p>
      <nav className="text-sm text-emerald-700 flex gap-4">
        <a href="/generator" className="underline">Generator</a>
        <a href="/blueprint-diet" className="underline">Blueprint Diet</a>
        <a href="/goals/weight-loss" className="underline">Goals</a>
      </nav>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    </section>
  );
}


